# Generated by Django 2.0.3 on 2018-07-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('example_desc', models.TextField()),
                ('keywords', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('relation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('pic_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WordExampleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.SmallIntegerField()),
                ('example_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvoexample.Example')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvoexample.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.SmallIntegerField()),
                ('word1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word1', to='pvoexample.Word')),
                ('word2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2', to='pvoexample.Word')),
            ],
        ),
    ]
