# Generated by Django 2.0.3 on 2018-07-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordrelation',
            name='word1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word1_id', to='pvoexample.Word'),
        ),
        migrations.AlterField(
            model_name='wordrelation',
            name='word2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2_id', to='pvoexample.Word'),
        ),
    ]
