# Generated by Django 2.0.3 on 2018-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0002_auto_20180716_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordexamplerelation',
            old_name='relation',
            new_name='relation_id',
        ),
        migrations.AlterField(
            model_name='example',
            name='keywords',
            field=models.TextField(default='nokeyword'),
        ),
        migrations.AlterField(
            model_name='example',
            name='relation',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(default='undefined'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pic_url',
            field=models.URLField(default=''),
        ),
    ]
