# Generated by Django 2.0.7 on 2018-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0005_auto_20180721_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pic_url',
        ),
        migrations.AddField(
            model_name='word',
            name='pic',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(default=''),
        ),
    ]
