# Generated by Django 2.0.7 on 2018-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0006_auto_20180817_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordrelation',
            name='word1_id',
        ),
        migrations.RemoveField(
            model_name='wordrelation',
            name='word2_id',
        ),
        migrations.AddField(
            model_name='wordrelation',
            name='word1',
            field=models.CharField(default='new word', max_length=50),
        ),
        migrations.AddField(
            model_name='wordrelation',
            name='word2',
            field=models.CharField(default='new word', max_length=50),
        ),
    ]
