# Generated by Django 2.0.7 on 2018-08-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0007_auto_20180826_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordrelation',
            name='word1',
        ),
        migrations.RemoveField(
            model_name='wordrelation',
            name='word2',
        ),
        migrations.AddField(
            model_name='wordrelation',
            name='word1_id',
            field=models.ForeignKey(default='NaN', on_delete=django.db.models.deletion.CASCADE, related_name='word1_id', to='pvoexample.Word'),
        ),
        migrations.AddField(
            model_name='wordrelation',
            name='word2_id',
            field=models.ForeignKey(default='NaN', on_delete=django.db.models.deletion.CASCADE, related_name='word2_id', to='pvoexample.Word'),
        ),
    ]
