# Generated by Django 2.0.7 on 2018-08-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0008_auto_20180827_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordrelation',
            name='word1_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='word1_id', to='pvoexample.Word'),
        ),
        migrations.AlterField(
            model_name='wordrelation',
            name='word2_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='word2_id', to='pvoexample.Word'),
        ),
    ]
