# Generated by Django 2.0.7 on 2018-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0009_auto_20180827_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrelation',
            name='word1',
            field=models.CharField(default='new word', max_length=50),
        ),
        migrations.AddField(
            model_name='wordrelation',
            name='word2',
            field=models.CharField(default='new word', max_length=50),
        ),
    ]
