# Generated by Django 2.0.7 on 2018-08-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0010_auto_20180827_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordrelation',
            name='word1_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='word1_id', to='pvoexample.Word'),
        ),
        migrations.AlterField(
            model_name='wordrelation',
            name='word2_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='word2_id', to='pvoexample.Word'),
        ),
    ]
