# Generated by Django 2.0.7 on 2018-08-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvoexample', '0011_auto_20180827_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordrelation',
            name='word1',
        ),
        migrations.RemoveField(
            model_name='wordrelation',
            name='word2',
        ),
    ]
